services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/redesfam
    restart: "no"  # El contenedor no iniciará automáticamente con el daemon
volumes:
  neo4j_data:
